### ISSUE TITLE
Latest release (0.2.9-rc.2) is missing the build directory

### ISSUE THREAD

**Issue by jall** [lightness/type-comparator#8]
I think the latest release is missing its `build` directory, which causes TS to fail to import anything.

The error message I get is `Cannot find module 'type-comparator' or its corresponding type declarations.ts(2307)`

Skimming the Github workflows file, it looks like there's no `npm build` step being called anywhere, just install and publish

**Comment by lightness** [comment]
Hi! Thanks a lot for this issue. I'll fix it asap

**Comment by lightness** [comment]
Fixed in `0.2.9-rc.3`... Sorry for delay and inconvenience

**Comment by lightness** [comment]
Feel free to reopen if something still wrong.
